name: flutter_qnote
description: AI_Qnote_app
version: 1.0.0+1

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0
  intl: ^0.18.0
  font_awesome_flutter: ^10.4.0
  http: ^1.4.0
  riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/kakao_login_large_wide.png
    - assets/images/qnote_icon.png

  fonts:
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf

    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo-Regular.ttf
