name: flutter_qnote
description: AI_Qnote_app
version: 1.0.0+1

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.2.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.4.0
  http: ^1.4.0
  riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  kakao_flutter_sdk: ^1.9.7+3
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/kakao_login_large_wide.png
    - assets/images/qnote_icon.png
    - assets/images/google_login_large_wide.png
    - assets/images/ai_avatar.png
    - .env

  fonts:
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf

    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo-Regular.ttf

    - family: InterVariable
      fonts:
        - asset: assets/fonts/InterVariable.ttf

  # 만약 intl 버전 충돌 발생 시 (table_calendar 등이 intl 0.18.x 요구 시)
dependency_overrides:
  intl: ^0.19.0