name: figma_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0
  intl: ^0.18.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf

    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo-Regular.ttf
